-- begin CMSCRDPROFILE
alter table CMSCRDPROFILE add constraint FK_CMSCRDPROFILE_ON_CRD_PRF_DET foreign key (CRD_PRF_DET_ID) references CMSCRDPROFILEDET(ID)^
alter table CMSCRDPROFILE add constraint FK_CMSCRDPROFILE_ON_CRD_EMV_KEY foreign key (CRD_EMV_KEY_ID) references CMSCRDEMVKEY(ID)^
create unique index IDX_CMSCRDPROFILE_UK_BIN on CMSCRDPROFILE (BIN) where DELETE_TS is null ^
create index IDX_CMSCRDPROFILE_ON_CRD_PRF_DET on CMSCRDPROFILE (CRD_PRF_DET_ID)^
create index IDX_CMSCRDPROFILE_ON_CRD_EMV_KEY on CMSCRDPROFILE (CRD_EMV_KEY_ID)^
-- end CMSCRDPROFILE
-- begin CMSCRDEMVKEY
create unique index IDX_CMSCRDEMVKEY_UK_BIN on CMSCRDEMVKEY (BIN) where DELETE_TS is null ^
-- end CMSCRDEMVKEY
-- begin CMSCRDEMVOLDKEY
create unique index IDX_CMSCRDEMVOLDKEY_UK_BIN on CMSCRDEMVOLDKEY (BIN) where DELETE_TS is null ^
-- end CMSCRDEMVOLDKEY
-- begin CMSCRDPROFILEDET
create unique index IDX_CMSCRDPROFILEDET_UK_BIN on CMSCRDPROFILEDET (BIN) where DELETE_TS is null ^
-- end CMSCRDPROFILEDET
-- begin CMSCARDGENREQDET
alter table CMSCARDGENREQDET add constraint FK_CMSCARDGENREQDET_ON_CARD_GEN foreign key (CARD_GEN_ID) references CMSCARDGENREQ(ID)^
create index IDX_CMSCARDGENREQDET_ON_CARD_GEN on CMSCARDGENREQDET (CARD_GEN_ID)^
-- end CMSCARDGENREQDET
-- begin CMSCRDCOND_ACCTTYPE
alter table CMSCRDCOND_ACCTTYPE add constraint FK_CMSCRDCOND_ACCTTYPE_ON_CARD_COND foreign key (CARD_COND_ID) references CMSCRDCOND(ID)^
create index IDX_CMSCRDCOND_ACCTTYPE_ON_CARD_COND on CMSCRDCOND_ACCTTYPE (CARD_COND_ID)^
-- end CMSCRDCOND_ACCTTYPE
-- begin CMSCRDCHRGS
alter table CMSCRDCHRGS add constraint FK_CMSCRDCHRGS_ON_CARD_PROFILE foreign key (CARD_PROFILE_ID) references CMSCRDPROFILE(ID)^
create index IDX_CMSCRDCHRGS_ON_CARD_PROFILE on CMSCRDCHRGS (CARD_PROFILE_ID)^
-- end CMSCRDCHRGS
-- begin CMSCRDDET
alter table CMSCRDDET add constraint FK_CMSCRDDET_ON_CARD_MAST foreign key (CARD_MAST_ID) references CMSCRDMAST(ID)^
create index IDX_CMSCRDDET_ON_CARD_MAST on CMSCRDDET (CARD_MAST_ID)^
-- end CMSCRDDET
-- begin CMSCRDACCT
alter table CMSCRDACCT add constraint FK_CMSCRDACCT_ON_CARD_DET foreign key (CARD_DET_ID) references CMSCRDDET(ID)^
create index IDX_CMSCRDACCT_ON_CARD_DET on CMSCRDACCT (CARD_DET_ID)^
-- end CMSCRDACCT
