alter table CMSCARDGENREQDET add constraint FK_CMSCARDGENREQDET_ON_BATCHNUM foreign key (BATCHNUM) references CMSCARDGENREQ(ID);
create index IDX_CMSCARDGENREQDET_ON_BATCHNUM on CMSCARDGENREQDET (BATCHNUM);
