alter table CMSCARDGENREQDET add constraint FK_CMSCARDGENREQDET_ON_CARD_GEN foreign key (CARD_GEN_ID) references CMSCARDGENREQ(ID);
create index IDX_CMSCARDGENREQDET_ON_CARD_GEN on CMSCARDGENREQDET (CARD_GEN_ID);
