create table CMSCARDGENREQ (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    BRN_CD varchar(10) not null,
    BATCHNUM varchar(4) not null,
    BATCHSTS varchar(5) not null,
    BIN varchar(10) not null,
    BTHREQ_DT date,
    CRDEMB_DT date,
    PINMLR_DT date,
    FILEUPL_DT date,
    REQ_USERID1 varchar(10),
    REQ_USERID2 varchar(10),
    EMB_USERID1 varchar(10),
    EMB_USERID2 varchar(10),
    MLR_USERID1 varchar(10),
    MLR_USERID2 varchar(10),
    FUL_USERID1 varchar(10),
    FUL_USERID2 varchar(10),
    BATCH_CNT integer,
    RENEW varchar(1),
    POSTGEN varchar(1),
    LAST_UPDATED date,
    STSUPD_USERID varchar(10),
    --
    primary key (ID)
);