create table CMSCRDPROFILE (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    BIN varchar(10),
    BIN_DESCR varchar(45),
    BINLEN integer,
    INSTNO integer,
    CRDLEN integer,
    PANLEN integer,
    CRD_FMT varchar(20),
    PVKI varchar(2),
    ENC_METHOD varchar(1),
    PIN_TYPE varchar(1),
    PIN_OFFSET integer,
    PAN_OFFSET integer,
    PIN_LEN integer,
    PIN_CHK_LEN integer,
    PAD_CHAR varchar(1),
    SER_VCD varchar(5),
    DEC_TBL varchar(16),
    MAILER_TYPE integer,
    PVK1 varchar(49),
    PVK1_KCV varchar(8),
    PVK2 varchar(49),
    PVK2_KCV varchar(8),
    CVK1 varchar(49),
    CVK1_KCV varchar(8),
    CVK2 varchar(16),
    CVK2_KCV varchar(8),
    PIN_ALG integer,
    CRD_TYPE varchar(15),
    CRD_PRF_DET_ID uuid not null,
    CRD_EMV_KEY_ID uuid not null,
    --
    primary key (ID)
);