alter table CMSCRDCHRGS add constraint FK_CMSCRDCHRGS_ON_CARD_PROFILE foreign key (CARD_PROFILE_ID) references CMSCRDPROFILE(ID);
create index IDX_CMSCRDCHRGS_ON_CARD_PROFILE on CMSCRDCHRGS (CARD_PROFILE_ID);
