create table CMSFEES_CHRGCD (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    INSTNO integer,
    CHRGCD varchar(10),
    CHRGCD_DESCR varchar(100),
    CHRGCD_CURR varchar(3),
    CHRGCD_TENORBY varchar(1),
    RATE1 integer,
    RATE2 integer,
    RATE3 integer,
    RATE4 integer,
    RATE5 integer,
    RATE6 integer,
    MINAMT integer,
    MAXAMT integer,
    TAMT1 integer,
    TAMT2 integer,
    TAMT3 integer,
    TAMT4 integer,
    TAMT5 integer,
    TAMT6 integer,
    FAMT1 integer,
    FAMT2 integer,
    FAMT3 integer,
    FAMT4 integer,
    FAMT5 integer,
    FAMT6 integer,
    GLCD varchar(20),
    LSTUPD date,
    --
    primary key (ID)
);