create table CMSCUSTCRDACCTDET (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    BIN varchar(10),
    CRDNUM varchar(16),
    CRD_ACCTNO varchar(18),
    CRD_ACCTTYPE varchar(2),
    CRD_ACCTCCY varchar(3),
    CRD_ACCTSTS varchar(1),
    CRD_OPT_PRIACCT varchar(1),
    CRD_OPT_FCSH varchar(1),
    CRD_OPT_CSH varchar(1),
    CRD_OPT_DEP varchar(1),
    CRD_OPT_INQ varchar(1),
    CRD_OPT_REQ varchar(1),
    CRD_OPT_TRF varchar(1),
    CRD_OPT_TRFDR varchar(1),
    CRD_OPT_TRFCR varchar(1),
    CRD_OPT_TRF3 varchar(1),
    CRD_OPT_TRF3DR varchar(1),
    CRD_OPT_TRF3CR varchar(1),
    CRD_OPT_IBFT varchar(1),
    CRD_OPT_IBFTDR varchar(1),
    CRD_OPT_IBFTCR varchar(1),
    --
    primary key (ID)
);