create table CMSCRDMAST (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    INSTNO integer,
    BIN varchar(10),
    CRDNUM varchar(16),
    CRDSTS varchar(2),
    CRD_CLSTYPE varchar(5),
    CRD_ISSUEDT date,
    CRD_ISSUED integer,
    CRD_CYCPRD integer,
    CRD_EMBOSSNM varchar(28),
    CRD_PINRETRIES_CNT integer,
    CRD_PINOFFSET varchar(12),
    CRD_PINSERIALNO varchar(18),
    CRD_EXPMTH varchar(2),
    CRD_EXPYR varchar(4),
    CRD_COLLECT_TYPE varchar(2),
    CRD_FCSH_AVL integer,
    CRD_FCSH_LMT integer,
    CRD_CSH_AVL integer,
    CRD_CSH_LMT integer,
    CRD_TRN_AVL integer,
    CRD_TRN_LMT integer,
    CRD_TRNDR_AVL integer,
    CRD_TRNDR_LMT integer,
    CRD_TRNCR_AVL integer,
    CRD_TRNCR_LMT integer,
    CRD_IBFT_AVL integer,
    CRD_IBFT_LMT integer,
    CRD_IBFTDR_AVL integer,
    CRD_IBFTDR_LMT integer,
    CRD_IBFTCR_AVL integer,
    CRD_IBFTCR_LMT integer,
    CRD_BILL_AVL integer,
    CRD_BILL_LMT integer,
    CRD_FREETXN_AVL integer,
    CRD_FREETXN_LMT integer,
    CRD_PINRETRIES_LMT integer,
    CRD_USE_AVL integer,
    CRD_USE_LMT integer,
    CRD_CARDSEQ integer,
    CRD_ATC varchar(4),
    CRD_LANGCD varchar(1),
    CRD_CHRGS_WAIVED varchar(1),
    CRD_PINTAGGED_DT date,
    CRD_ACCTLINK_DT date,
    CRD_COLLECT_DT date,
    CRD_CLOSE_DT date,
    CRD_LASTACCCHG_DT date,
    CRD_LASTACT_DT date,
    CRD_LASTMAINT_DT date,
    CRD_LASTSTSCHG_DT date,
    CRD_LASTCYC_DT date,
    --
    primary key (ID)
);